### ISSUE TITLE
Remove old value from cache when new value is set

### ISSUE THREAD

**Issue by jstewmc** [jstewmc/gravity#21]
We need to invalidate a cached value, if it exists, when a new value is set. Otherwise, the cached value will always be returned. 

Hmm, this may involve moving the cache to the manager? Otherwise, how would the manager communicate to the get-definition service that it needs to delete a cached value?

**Comment by jack-clayton** [comment]
Maybe we should think of the cache as a service, not a data object. If it's a service, we can inject the same instance in as many services as need it. We don't have to move it outside the _get-definition_ service, because the Manager and the service can have the same instance. 

It does involve state, though. So, it's not technically a service. It's really storage. Can we use PHP's pass-by-reference to inject a storage container as if it was a service. Maybe the [SODO design pattern](https://github.com/jstewmc/sodo-design-pattern) is missing a third type of object, storage?

**Comment by jstewmc** [comment]
Hmm, I think we can close this bug as it's no longer relevant. With the refactoring of the manager in PR #34, setting things after they are cached is no longer a problem. You can't set services or settings outside of files; no third-party services or settings should be instantiated while reading from the filesystem; and, if multiple files define the same service or setting, the last one wins. 

When\if we do add the ability to set services and settings back to the manager, we'll need to reconsider this one.
